SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `accounts`;
DROP TABLE IF EXISTS `aspect_type`;
DROP TABLE IF EXISTS `aspects`;
DROP TABLE IF EXISTS `companies`;
DROP TABLE IF EXISTS `company_categories`;
DROP TABLE IF EXISTS `company_features`;
DROP TABLE IF EXISTS `company_keywords`;
DROP TABLE IF EXISTS `company_keywords_link`;
DROP TABLE IF EXISTS `dashboard`;
DROP TABLE IF EXISTS `dashboard_settings`;
DROP TABLE IF EXISTS `data_cache`;
DROP TABLE IF EXISTS `feedback`;
DROP TABLE IF EXISTS `feedback_text`;
DROP TABLE IF EXISTS `locations`;
DROP TABLE IF EXISTS `milestone_aspects`;
DROP TABLE IF EXISTS `milestones`;
DROP TABLE IF EXISTS `notification_type`;
DROP TABLE IF EXISTS `notifications`;
DROP TABLE IF EXISTS `promo_codes`;
DROP TABLE IF EXISTS `session_data`;
DROP TABLE IF EXISTS `session_data_field`;
DROP TABLE IF EXISTS `store_features`;
DROP TABLE IF EXISTS `stores`;
DROP TABLE IF EXISTS `subscriptions`;
DROP TABLE IF EXISTS `support`;
DROP TABLE IF EXISTS `support_responses`;
DROP TABLE IF EXISTS `tablet_commands`;
DROP TABLE IF EXISTS `tablets`;
DROP TABLE IF EXISTS `transactions`;
DROP TABLE IF EXISTS `user_agents`;

SET FOREIGN_KEY_CHECKS = 1;
